### PR TITLE
fix: fix #111 by generating sourcemaps even when a previous loader didn't pass them

### LINKED ISSUE #111: imports-loader doesn't generate source maps by default
### Actual Behavior

My `rules` config looks like this:

```javascript
{
    rules: [
        {
            test: /\.jsx?$/,
            use: [{
                loader: "imports-loader",
                options: {
                    additionalCode: 'console.log("hello");'
                }
            }],
            exclude: /node_modules/,
        }
    ]
}
```

When I bundle a JS file using this config and then look at the source-mapped output in the Chrome debugger, the code injected by `imports-loader` is visible at the top of the file:

```javascript
/*** IMPORTS FROM imports-loader ***/


console.log("hello");
```

### Expected Behavior

The code injected by `imports-loader` should not be visible in the source mapped output.

### How Do We Reproduce?

1. Set up a webpack config with source maps enabled (eg `devTool: "inline-source-map"`).
2. Set up an `imports-loader` with `test: /\.jsx?$/`
3. Bundle a single `.js` file
4. Look at the source-mapped version of that file in the Chrome dev tools

### Other notes

* Source mapping works correctly when using `imports-loader` alongside other loaders which generate source maps (eg `ts-loader`)
* The [existing test](https://github.com/webpack-contrib/imports-loader/blob/master/test/loader.test.js#L326) doesn't detect the bug because it's plugged in `babel-loader` before the `imports-loader`
* I think the bug is in [this `if` statement](https://github.com/webpack-contrib/imports-loader/blob/master/src/index.js#L77) - it needs an `else if (this.sourceMap)` block in which we create a new sourcemap.

### PR DESCRIPTION
**Pull request by benjamin-hodgson**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

See isse #111. `imports-loader` was only generating sourcemaps when a previous loader in the chain had already provided one. Webpack itself still generates a sourcemap in these conditions, but it was incorrect due to the missing mappings for the code injected by `imports-loader`.

There is probably some room for improvement here, would be good to map an artificial source file for the code which was injected by `imports-loader`.

The existing tests were not very good - they checked that the compilation had run and produced an output JS file, but didn't even check that sourcemaps had been generated, let alone that the sourcemap was correct.

### CODE REVIEW

File: test/helpers/readAsset.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import path from "path";
 
-export default (asset, compiler, stats) => {
-  const usedFs = compiler.outputFileSystem;
+export default (asset, stats) => {
```
Comment (alexander-akait) [inline test/helpers/readAsset.js:3]: Avoid these changes, it is auto generated utils

File: test/__snapshots__/loader.test.js.snap [hunk 2]
```diff
@@ -1113,22 +1097,6 @@ var someCode = {
...
-
-var someCode = {
-  number: 123,
-  object: {
-    existingSubProperty: 123
-  }
-};"
-`;
-
-exports[`loader should work with source maps when the "devtool" option is enabled: warnings 1`] = `Array []`;
```
Comment (alexander-akait) [inline test/__snapshots__/loader.test.js.snap:1130]: Do not remove tests

File: test/helpers/readAsset.js (hunk 1 above)
Comment (benjamin-hodgson) [reply test/helpers/readAsset.js:3]: Where are they generated from?

File: test/__snapshots__/loader.test.js.snap (hunk 2 above)
Comment (benjamin-hodgson) [reply test/__snapshots__/loader.test.js.snap:1130]: I didn't remove the test, I rewrote it.

File: test/helpers/readAsset.js (hunk 1 above)
Comment (alexander-akait) [reply test/helpers/readAsset.js:3]: From our boilerplace

Comment (benjamin-hodgson) [reply test/helpers/readAsset.js]: b6c480a2849b9a09c5769ef5d313af5741cbe4ff

**Comment by benjamin-hodgson** [comment]
Thank you!
